#!/bin/bash

VERSION="1.1.0"

rm -rf atomes-$VERSION
tar -zxf atomes-$VERSION.tar.gz
rm -f atomes-$VERSION.tar.gz
cd atomes-$VERSION
export DEBEMAIL="sebastien.leroux@ipcms.unistra.fr"
export export DEBFULLNAME="Sébastien Le Roux"
dh_make --createorig -s -y
dpkg-buildpackage
cd ..
scp * leroux@pc-chess:files/git-files/atomes/atomes-deb-build/atomes-deb-build/
