Document: atomes
Title: Debian atomes Manual
Author: Sébastien Le Roux
Abstract: Atomes: a toolbox to analyze, visualize and edit/create 3D atomistic models.

Section: Science

Format: debiandoc-sgml
Files: /usr/share/doc/atomes/atomes.sgml.gz

Format: postscript
Files: /usr/share/doc/atomes/atomes.ps.gz

Format: text
Files: /usr/share/doc/atomes/atomes.text.gz

Format: HTML
Index: /usr/share/doc/atomes/html/index.html
Files: /usr/share/doc/atomes/html/*.html
