.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2022 Sébastien Le Roux <sebastien.leroux@ipcms.unistra.fr>,
.\"
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH Atomes 1 "September  2 2022"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
atomes \- a toolbox to analyze, visualize and create/edit 3D atomistic models
.SH SYNOPSIS
.B atomes
.RI [ options ] " files" ...
.br
.SH DESCRIPTION
This manual page documents briefly the
.B atomes
command.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics,
.\" respectively.
\fBatomes\fP is a toolbox to analyze, visualize and edit/create 3D atomistic models. 

It offers a workspace to open and manage project(s) that can exchange data: analysis results, atomic coordinates ...

\fBatomes\fP also provides an advanced input preparation system for calculations
using well know molecular dynamics codes:

.RS
.B Classical MD:
.IR DLPOLY
and 
.IR LAMMPS
.RE
.RS
.B Ab-initio MD:
.IR CPMD
and 
.IR CP2K
.RE
.RS
.B QM-MM MD:
.IR CPMD
and 
.IR CP2K
.RE

.SH OPTIONS
This program follows the usual GNU command line syntax, with long
options starting with two dashes (`-').
A summary of options is included below.
For a complete description, see the Info files.
.TP
.B \-awf, -AWF
Open atomes workspace file.
.TP
.B \-apf, -APF
Open atomes project file(s).
.TP
.B \-xyz, -XYZ
Import XYZ atomic coordinates(s).
.TP
.B \-pdb, -PDB
Import PDB atomic coordinates(s).
.TP
.B \-cif, -CIF
Import CIF atomic coordinate(s).
.TP
.B \-h, \-\-help
Show summary of options.
.TP
.B \-v, \-\-version
Show version of program.
.SH SEE ALSO
.BR https://atomes.ipcms.fr/

.SH AUTHOR
This manual page was created by Sébastien Le Roux <sebastien.leroux@ipcms.unistra.fr>
