#!/bin/bash

function list_files_in_dir {
  hdir=$1
  ldir=$2
  cd $hdir
  echo "debian/tmp/usr/share/atomes/"$ldir >> ~/files/deb-files/debian-package-data/liste
  ls -l |awk '/^-/ {print "debian/tmp/usr/share/atomes/'$ldir'/"$NF}' >> ~/files/deb-files/debian-package-data/liste
  ndir=`ls -l |awk '/^d/ {print $NF}'|wc -l`
  if [ $ndir -ne 0 ]; then
    listed=`ls -l |awk '/^d/ {printf $NF" "}'`
    echo "listed= "$listed
    for di in $listed
    do
     sldir=
     ndi=`echo $ldir"/"$di`
     echo "ndi= "$ndi
     list_files_in_dir $di $ndi
    done
  fi
  cd ..
}

rm -f liste
rootdir="../atomes-1.1.12/libs"
echo "rootdir= "$rootdir
listedir=`ls -l $rootdir|awk '/^d/ {printf $NF" "}'`
echo "listedir= "$listedir
for dir in $listedir
do
  cd $rootdir
  list_files_in_dir $dir $dir
  cd ~/files/deb-files/debian-package-data/
done

